### ISSUE TITLE
Support for SHA1 at end of upload

### ISSUE THREAD

**Issue by Boscop** [Darksonn/backblaze-b2-rs#1]
B2 allows uploading by providing the SHA1 at the end of the upload, this is very useful for servers that want to offload user uploaded files to b2 by directly streaming the file being uploaded instead of first uploading the whole file to the server and then computing the SHA1 before uploading to b2:
https://www.backblaze.com/b2/docs/uploading.html
Is there a plan to support this in this lib? It would be easy to implement.
The API in this lib could be similar to the b2 API:
There would be a function similar to [this](https://docs.rs/backblaze-b2/0.1.4/backblaze_b2/raw/upload/struct.UploadAuthorization.html#method.upload_file):
```rust
fn upload_file_sha1_at_end<InfoType, R: Read, C, S>(
    &self, 
    file: &mut R, 
    file_name: String, 
    content_type: Option<Mime>, 
    content_length: u64, 
    connector: &C
) -> Result<MoreFileInfo<InfoType>, B2Error> 
```
And it just forwards the reader, i.e. assumes that the last 40 bytes are the SHA1.

The alternative would be to change `upload_file()` to take `content_sha1: Option<String>` but that'd be more ambiguous, people might think not providing the SHA1 would be equivalent to `X-Bz-Content-Sha1: do_not_verify`. 
(Btw, maybe that should also be supported, then this should mean that, IMO.)

**Comment by Darksonn** [comment]
As of version `0.1.5` this is possible using the method `create_upload_file_request_sha1_at_end` on the `UploadAuthorization` struct.

The documentation for this new method can be found [here][1].

If you really want to use `do_not_verify`, pass that string as the sha1. I added a note about that in the documentation.

 [1]: https://docs.rs/backblaze-b2/0.1.5/backblaze_b2/raw/upload/struct.UploadAuthorization.html#method.create_upload_file_request_sha1_at_end
