### ISSUE TITLE
I plan to use it in rdedup

### ISSUE THREAD

**Issue by dpc** [Darksonn/backblaze-b2-rs#7]
Hi,

This is a really nice crate! I was looking through the documentation, and it is really well done. I wish the "higher-level" API was available, but the "raw" one is actually exactly what I would expect.

I have a couple of questions. 

Is multi-threaded usage working well? I plan to employ a thread-pool, so just double checking.

Are you aware if keepalive is working? I'm looking at https://www.reddit.com/r/rust/comments/6zm1uq/backblaze_reqwest_and_keepalive/ and for `rdedup` it is going to be very important to be able to efficiently upload many, many small files. Having a working keep-alive could keep the link saturated, even with many very small files being uploaded.

Do you think there are any other things (especially any current shortcomings) that I should be aware of?

Anyway, thank you very much for this crate, it will make my task much easier!

**Comment by Darksonn** [comment]
I'm not aware of any issues with multi-threaded usage except for the fact that according to the official backblaze documentation, you can't upload several things to one upload url simultaneously, which means that you will need to create a new UploadAuthorization for each thread.

I don't know if keep-alive is working, but it might be a setting you need to set on the [Client](https://docs.rs/hyper/0.10.12/hyper/client/struct.Client.html) object, which you need to create yourself anyway. If you find out more about keep-alive, please tell me.

The large-files api is not currently implemented.

The newest version is currently `0.1.9-2`.

**Comment by dpc** [comment]
Thank you. I will update you once I do it.
